FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /mainApp

COPY . .

RUN dotnet restore
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .

ENV ASPNETCORE_URLS="http://0.0.0.0:5015"
ENV ASPNETCORE_ENVIRONMENT="Production"

ENTRYPOINT [ "dotnet", "NetTemplate.dll" ]